# cloudbuild.yaml
options:
  logging: "CLOUD_LOGGING_ONLY"

steps:
  # Step 1: Install dependencies for the Cloud Functions
  - name: 'node:18' 
    id: 'Install dependencies'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cd functions
        npm install

  # Step 2: Deploy the Cloud Function to Google Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Cloud Function'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud functions deploy $_SERVICE_NAME \
          --region $_REGION \
          --service-account $_SERVICE_ACCOUNT \
          --runtime nodejs18 \
          --source functions \
          --trigger-http \
          --allow-unauthenticated

substitutions:
  _PROJECT_ID: "$PROJECT_ID"
  _SERVICE_NAME: "chatWithAI" # Cloud Function name
  _REPO_NAME: "littlefinger-backend-repo" # Not required for Cloud Functions but can be used for consistency
  _REGION: "us-central1"
  _SERVICE_ACCOUNT: "saib-ai-playground-sa@saib-ai-playground.iam.gserviceaccount.com"

timeout: '1200s'
