serviceAccount: "saib-ai-playground-sa@saib-ai-playground.iam.gserviceaccount.com"

options:
  logging: "CLOUD_LOGGING_ONLY"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/onchain-listeners:$COMMIT_SHA', '.']
    dir: 'onchain-listeners'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/onchain-listeners:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'onchain-listeners',
         '--image', 'gcr.io/$PROJECT_ID/onchain-listeners:$COMMIT_SHA',
         '--region', 'asia-southeast1',
         '--allow-unauthenticated',
         '--service-account', 'saib-ai-playground-sa@saib-ai-playground.iam.gserviceaccount.com']
