name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 4: Authenticate with Service Account
      - name: Authenticate with Service Account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > $HOME/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
          echo "Service account credentials written to $HOME/service-account.json"
          cat $HOME/service-account.json | jq .client_email

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json
        run: |
          set -e
          firebase deploy --only hosting
